@startuml
object products {
    id: pk
    title: string
    price: number
    variation: string
    shop_id: fk
}

object orders {
    id: pk
    user_id: fk
}

object order_carts {
    id: pk
    variation_id: fk
    order_id: fk
}

object users {
    id: pk
    email: string
    name: string
}

object shops {
    id: pk
    name: string
}

object variations {
    id: pk
    product_id: fk
    color: string
    size: enum(S, M, L, LL, 2L, 3L...)
}

products "*" -- "1" shops
users "1" -- "*" orders
orders "*" -- "*" products
order_carts "*" -- "1" orders
order_carts "*" -- "1" variations
products "1" -- "*" variations
@enduml